### ISSUE TITLE
wan connectivity checks - doc missing?

### ISSUE THREAD

**Issue by marafa-sugarcrm** [CloudFire-LLC/cloudfire#1576]
**Describe the bug**
i see https://github.com/firezone/firezone/blob/78f8d46da7519bc31c5d02b1b53253081716eb26/apps/fz_http/lib/fz_http_web/live/connectivity_check_live/index_live.ex#L1
but while searching the docs for `wan connectivity checks' nothing shows up. either it isnt published or the search function doesnt work :/ 

also, not really sure why this is needed. firezone works for me
![Screenshot 2023-04-27 at 8 02 53 AM](https://user-images.githubusercontent.com/69474017/234856122-9b30fcca-c677-4519-8bd0-12b84e601d11.png)

what needs to be done to allow this method?

**To Reproduce**

**Expected behavior**

**Screenshots / Logs**
If applicable, add screenshots and log traces to help debug your problem with any sensitive data removed.

**Platform (please complete the following information):**
 - Firezone Version [e.g. 0.7.12]
 - OS: [e.g. Linux]
 - Distro: [e.g. Ubuntu 18.04]
 - Kernel version: [e.g. 5.10.11]
 - Deployment method: [e.g. Docker / Omnibus / Source]

**Additional context**

**Comment by jamilbk** [comment]
@marafa-sugarcrm Thanks for the report. This was used to generate the `Endpoint` field in WireGuard configs, but we fallback to another method now. The error you're seeing should have been fixed -- try upgrading to a later version (0.7.26).

**Comment by edvegas** [comment]
0.7.28 error still occurs - Method Not Allowed

**Comment by jamilbk** [comment]
Thanks for the note -- 0.7.29 should resolve this issue.

**Comment by marafa-sugarcrm** [comment]
thank you for fixing the check
however, i still do not see a doc link for this function
