### ISSUE TITLE
SSH connection drops after some time

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#6347]
This may be the issue reported by users on macOS. Will retest with more detailed logs, but I noticed this after about an hour of keeping the SSH connection open to a Vultr host.

```
handle_timeout{cid=a2536d4e-356a-45ca-8e7f-d8b551c02355}: snownet::node: Updating remote socket old=Some(Direct { source: 192.168.1.225:59467, dest: 64.176.12.220:51311 }) new=Direct { source: [2600:1700:3ecb:2410:fc11:edbf:ac6e:5746]:56644, dest: [2600:1900:4020:8f68:0:5e::]:64201 } duration_since_intent=5106.343569375s
```

There was no `Connection idle` message in the client logs. Seems like the connection got dropped somehow.

[Archive.zip](https://github.com/user-attachments/files/16662292/Archive.zip)

**Comment by jamilbk** [comment]
I'm not sure this would be affected by #6332 since the hole-punching succeeded.

**Comment by jamilbk** [comment]
Note this is with the latest release Gateway running inside docker.

**Comment by jamilbk** [comment]
Looks like the hole-punch is getting dropped or reset or something. This is with latest release Gateway (1.1.5) in Docker. Logs corresponding to the above:

```
2024-08-19T15:22:46.044836Z  INFO handle_timeout{cid=91b9f3e6-7b9c-465f-aca8-9f4d7e8c4e3b}: snownet::node: Updating remote socket old=Some(Direct { source: 172.17.0.2:51311, dest: 107.197.104.68:59467 }) new=Relay { relay: 6fa51389-fc22-49d5-b3dc-0bf1edb59fec, dest: [2600:1700:3ecb:2410:fc11:edbf:ac6e:5746]:56644 } duration_since_intent=5106.25s
2024-08-19T15:25:33.029509Z  INFO snownet::allocation: Updated allocation srflx_ip4=Some(64.176.12.220:51311) srflx_ip6=None relay_ip4=Some(34.151.244.244:63441) relay_ip6=Some([2600:1900:40f0:287:0:2a::]:63441) remaining_lifetime=Some(600s)
2024-08-19T15:25:38.805866Z  INFO handle_timeout{cid=91b9f3e6-7b9c-465f-aca8-9f4d7e8c4e3b}: snownet::node: Connection failed (ICE timeout)
```

**Comment by jamilbk** [comment]
Notice the direct connection failed established originally failed and it moved to a Relayed connection. Since the Gateway reported the ICE timeout perhaps there is an issue on macOS or in my local network with the socket being closed or something? Here's the Gateway log where the holepunch succeeded prior:

```
2024-08-19T13:57:39.681923Z  INFO accept_connection{cid=91b9f3e6-7b9c-465f-aca8-9f4d7e8c4e3b}: snownet::node: Created new connection
2024-08-19T13:57:40.221912Z  INFO handle_timeout{cid=91b9f3e6-7b9c-465f-aca8-9f4d7e8c4e3b}: snownet::node: Updating remote socket old=None new=Direct { source: 172.17.0.2:51311, dest: 34.102.39.122:50177 } duration_since_intent=373.310041ms
2024-08-19T13:57:40.297524Z  INFO handle_timeout{cid=91b9f3e6-7b9c-465f-aca8-9f4d7e8c4e3b}: snownet::node: Updating remote socket old=Some(Direct { source: 172.17.0.2:51311, dest: 34.102.39.122:50177 }) new=Direct { source: 172.17.0.2:51311, dest: 107.197.104.68:59467 } duration_since_intent=373.310041ms
2024-08-19T13:57:40.360544Z  INFO connection{cid=91b9f3e6-7b9c-465f-aca8-9f4d7e8c4e3b}: snownet::node: Completed wireguard handshake duration_since_intent=679.395309ms
```

I wonder if this is the same issue that was seen by @conectado with holepunched connections failing after a minute or two. Perhaps there are more NATs in the wild (my home router included) that having the same issue as #6290 or we somehow roll the source port over by accident somewhere.

**Comment by jamilbk** [comment]
To add more, it looks like the connection went idle (!!) for an SSH session, causing a noticeable delay when I tried to use the SSH session again.


```
2024-08-19T17:15:48.331053Z  INFO handle_timeout{cid=91b9f3e6-7b9c-465f-aca8-9f4d7e8c4e3b}: snownet::node: Connection is idle
2024-08-19T17:15:49.786157Z  INFO snownet::allocation: Updated allocation srflx_ip4=Some(64.176.12.220:51311) srflx_ip6=None relay_ip4=Some(104.196.33.29:64201) relay_ip6=Some([2600:1900:4020:8f68:0:5e::]:64201) remaining_lifetime=Some(600s)
2024-08-19T17:18:16.455134Z  INFO accept_connection{cid=91b9f3e6-7b9c-465f-aca8-9f4d7e8c4e3b}: snownet::node: Created new connection
2024-08-19T17:18:17.071363Z  INFO handle_timeout{cid=91b9f3e6-7b9c-465f-aca8-9f4d7e8c4e3b}: snownet::node: Updating remote socket old=None new=Direct { source: 172.17.0.2:51311, dest: 107.197.104.68:61678 } duration_since_intent=599.481878ms
2024-08-19T17:18:17.261789Z  INFO connection{cid=91b9f3e6-7b9c-465f-aca8-9f4d7e8c4e3b}: snownet::node: Completed wireguard handshake duration_since_intent=806.823456ms
```

Would it make sense to increase the idle timeout if it's not as well behaved as we suspect? Or there's a bug that's causing `snownet` to fail to detect idle connections properly.

**Comment by jamilbk** [comment]
Yeah I can reliably reproduce `Connection is idle` for SSH sessions. I wonder if this will cause issues if the portal picks a different Gateway for resuming the SSH session than what was originally used to establish it. Based on [this page](https://en.wikipedia.org/wiki/Keepalive) it seems like the keepalive time is `2 hours` (!!) on Windows and Linux, which means a keepalive won't be sent for 2 hours on idle connections?

**Comment by thomaseizinger** [comment]
> I wonder if this will cause issues if the portal picks a different Gateway for resuming the SSH session than what was originally used to establish it.

It should be deterministic right? And we don't have multi-site resources yet so even if we established a different connection in the meantime (and we thus send a list of connected gateways), the same gateway should be picked for the same resource.

**Comment by conectado** [comment]
> > I wonder if this will cause issues if the portal picks a different Gateway for resuming the SSH session than what was originally used to establish it.
> 
> It should be deterministic right? And we don't have multi-site resources yet so even if we established a different connection in the meantime (and we thus send a list of connected gateways), the same gateway should be picked for the same resource.

@thomaseizinger  If it's the only connection, the gateway might change to a different one in the same site, since we send the portal the current list of connected gateways.

**Comment by thomaseizinger** [comment]
> > > I wonder if this will cause issues if the portal picks a different Gateway for resuming the SSH session than what was originally used to establish it.
> > 
> > 
> > It should be deterministic right? And we don't have multi-site resources yet so even if we established a different connection in the meantime (and we thus send a list of connected gateways), the same gateway should be picked for the same resource.
> 
> @thomaseizinger If it's the only connection, the gateway might change to a different one in the same site, since we send the portal the current list of connected gateways.

Ah you are right. I am not sure if there is much we can do about it then?

**Comment by conectado** [comment]
> > > > I wonder if this will cause issues if the portal picks a different Gateway for resuming the SSH session than what was originally used to establish it.
> > > 
> > > 
> > > It should be deterministic right? And we don't have multi-site resources yet so even if we established a different connection in the meantime (and we thus send a list of connected gateways), the same gateway should be picked for the same resource.
> > 
> > 
> > @thomaseizinger If it's the only connection, the gateway might change to a different one in the same site, since we send the portal the current list of connected gateways.
> 
> Ah you are right. I am not sure if there is much we can do about it then?

We could try to remember the gateways that we have connected to in the past? So in case it's still available we will pick that one, should be relatively easy to do, except for how long we keep that buffer alive but we can keep a buffer of the last 100 gateways for just 1.6 kB of memory

**Comment by thomaseizinger** [comment]
That would also reduce roundtrips because we don't need to send as many connection intents.

**Comment by conectado** [comment]
> That would also reduce roundtrips because we don't need to send as many connection intents.

I think we would still need the same number of connection intents? We still need to send the intent to get the gateway we use since it might be down.

**Comment by jamilbk** [comment]
If the TCP keepalive is 2 hours, and the NAT(s) treat TCP and UDP differently, it's entirely possible that behavior with Firezone enabled would be different than without. I.e. it could close our NAT session for UDP where in the same case SSH might have lived longer. In that case increasing the idle timeout to 2 hours might not even prevent the SSH connection issue, and #6335 has a better chance of improving this. Just thought I'd check my thinking here.

**Comment by jamilbk** [comment]
> If the TCP keepalive is 2 hours, and the NAT(s) treat TCP and UDP differently, it's entirely possible that behavior with Firezone enabled would be different than without. I.e. it could close our NAT session for UDP where in the same case SSH might have lived longer. In that case increasing the idle timeout to 2 hours might not even prevent the SSH connection issue, and #6335 has a better chance of improving this. Just thought I'd check my thinking here.

Nevermind - in most cases the server will have an inbound port mapped for non-Firezone cases and NAT sessions won't really come into play like I describe above.

**Comment by thomaseizinger** [comment]
> > That would also reduce roundtrips because we don't need to send as many connection intents.
> 
> I think we would still need the same number of connection intents? We still need to send the intent to get the gateway we use since it might be down.

Ah, are you saying we would simply include the previously connected gateway in `connected_gateways`?

**Comment by conectado** [comment]
> > > That would also reduce roundtrips because we don't need to send as many connection intents.
> > 
> > 
> > I think we would still need the same number of connection intents? We still need to send the intent to get the gateway we use since it might be down.
> 
> Ah, are you saying we would simply include the previously connected gateway in `connected_gateways`?

yeah, easy change to do, and it's probably a good one overall

**Comment by thomaseizinger** [comment]
> > > > That would also reduce roundtrips because we don't need to send as many connection intents.
> > > 
> > > 
> > > I think we would still need the same number of connection intents? We still need to send the intent to get the gateway we use since it might be down.
> > 
> > 
> > Ah, are you saying we would simply include the previously connected gateway in `connected_gateways`?
> 
> yeah, easy change to do, and it's probably a good one overall

Done: https://github.com/firezone/firezone/pull/6361.

**Comment by jamilbk** [comment]
Seems to be fixed with the sticky Gateways fix.

**Comment by jamilbk** [comment]
User reports this is still an issue, reopening. Behavior is that connection lags / hangs after some time.

I think the idle timeout might be less than SSH keepalive.

**Comment by thomaseizinger** [comment]
> I think the idle timeout might be less than SSH keepalive.

Yeah, didn't we see that it was 2+ hours?

I think this will be fixed by packet-buffering. With the sticky gateways, interacting the SSH again, should send more packets which - as soon as we don't drop them anymore - should just reestablish things (assuming the NAT port on the gateway is free but it should be in most cases).

**Comment by jamilbk** [comment]
Customer reporting this still to be an issue. If we buffer the connection intent I _think_ that would solve it, assuming the underlying TCP connection is able to get re-established just like if running without Firezone.

Going to bump priority.

**Comment by jamilbk** [comment]
Wondering if it just makes sense to extend the idle timeout to something like 8 hours for desktop clients and gateways. That should solve this issue immediately and the power/network savings is probably miniscule
.

**Comment by thomaseizinger** [comment]
> Customer reporting this still to be an issue. If we buffer the connection intent I _think_ that would solve it, assuming the underlying TCP connection is able to get re-established just like if running without Firezone.
> 
> Going to bump priority.

Yeah, I can start working on the new control protocol next week. That will unblock buffering.

**Comment by thomaseizinger** [comment]
> Wondering if it just makes sense to extend the idle timeout to something like 8 hours for desktop clients and gateways. That should solve this issue immediately and the power/network savings is probably miniscule .

If clients and gateways don't agree on connection timeouts, we will see a lot more ICE timeouts in the logs. Not harmful but could make debugging more difficult.

I'd consider that more of a hack than a solution.

**Comment by jamilbk** [comment]
> > Wondering if it just makes sense to extend the idle timeout to something like 8 hours for desktop clients and gateways. That should solve this issue immediately and the power/network savings is probably miniscule .
> 
> If clients and gateways don't agree on connection timeouts, we will see a lot more ICE timeouts in the logs. Not harmful but could make debugging more difficult.
> 
> I'd consider that more of a hack than a solution.

Suggested they try adding this to their ~/.ssh/config

```
Host *
    ServerAliveInterval 240
```

which should send a null packet every 4 minutes to keep things alive. Currently a blocker for them I think so if that doesn't do maybe we can implement the hack and then revert it when buffering is complete. Otherwise it might block things from moving forward.

**Comment by thomaseizinger** [comment]
SGTM. If the keep-alive doesn't fix it or they don't want to use it, we can implement an configuration value for the idle connection timeout?
