### ISSUE TITLE
Buffer packets / messages room join is ack'd

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#9647]
In the following failing CI run, the client quickly sent 4 packets after joining the portal channel but before receiving the `init`.

https://github.com/firezone/firezone/actions/runs/15833197977/job/44630996543?pr=9646

In the portal, there is some small amount of time required to set up the client's websocket, which ensures its presence is being tracked appropriately. Messages sent from the client to the portal before this won't be broadcasted to gateway appropriately, leading to dropped messages.

To prevent this, ideally the client should buffer packets until it has received the `init` message acknowledging the client.

**Comment by jamilbk** [comment]
This would be an issue during portal reconnects - here it seems to be the case this is hitting the `30s` curl timeout.

**Comment by thomaseizinger** [comment]
> To prevent this, ideally the client should buffer packets until it has received the `init` message acknowledging the client.

Is this really necessary?

Tracking `init` inside phoenix-channel is quite hacky because it is an application-level message and has nothing to do with the phoenix data model.

We can track the joining of the room but we do send the join before all other messages so it should be set up by the time the other messages arrive.

Buffering this on the client sounds like a workaround to me. If the portal isn't ready to process messages on the socket, it shouldn't read from it. This will then back-pressure via TCP down to the client/gateway.

**Comment by jamilbk** [comment]
You probably don't even need to wait for the `init`. It looks like you're sending messages before phoenix has acknowledged your channel join:

```
client-1  | 2025-06-23T19:31:57.350Z TRACE wire::api::send: {"topic":"client","event":"phx_join","payload":null,"ref":5}
client-1  | 2025-06-23T19:31:57.350Z TRACE wire::api::send: {"topic":"client","event":"create_flow","payload":{"resource_id":"ce795e05-0d3a-441a-920b-ed5ae21695af","connected_gateway_ids":[]},"ref":1}
client-1  | 2025-06-23T19:31:57.350Z TRACE wire::api::send: {"topic":"client","event":"create_flow","payload":{"resource_id":"ce795e05-0d3a-441a-920b-ed5ae21695af","connected_gateway_ids":[]},"ref":2}
client-1  | 2025-06-23T19:31:57.350Z TRACE wire::api::send: {"topic":"client","event":"create_flow","payload":{"resource_id":"ce795e05-0d3a-441a-920b-ed5ae21695af","connected_gateway_ids":[]},"ref":3}
client-1  | 2025-06-23T19:31:57.350Z TRACE wire::api::send: {"topic":"client","event":"create_flow","payload":{"resource_id":"ce795e05-0d3a-441a-920b-ed5ae21695af","connected_gateway_ids":[]},"ref":4}
client-1  | 2025-06-23T19:31:57.353Z TRACE wire::api::recv: {"event":"phx_reply","ref":5,"topic":"client","payload":{"status":"ok","response":{}}}
```

**Comment by jamilbk** [comment]
Phoenix doesn't expose the TCP sockets to us, so if we want control over things at such a low level, we'll need to use something like https://www.erlang.org/doc/apps/kernel/gen_tcp.html

Which means we'll need to re-implement everything from HTTP to WebSocket up to the CRDT Phoenix.Channel and Phoenix.Presence use for state tracking across WebSocket topics.

**Comment by thomaseizinger** [comment]
> It looks like you're sending messages before phoenix has acknowledged your channel join:

Yeah we did that to keep the complexity low. State management of the phoenix channel already caused enough bugs as it is.

**Comment by jamilbk** [comment]
There won't be anything we can do on the portal side here unless we want to re-implement vast swaths of the Phoenix stack. I.e. we can't even "see" the client yet when these messages are arriving.

**Comment by thomaseizinger** [comment]
> Phoenix doesn't expose the TCP sockets to us, so if we want control over things at such a low level, we'll need to use something like https://www.erlang.org/doc/apps/kernel/gen_tcp.html
> 
> Which means we'll need to re-implement everything from HTTP to WebSocket up to the CRDT Phoenix.Channel and Phoenix.Presence use for state tracking across WebSocket topics.

I am not saying to re-implement it. I am saying it sounds like a bug in Phoenix that it is processing messages without handling them.

If where you are delivering messages to isn't ready to handle messages, you should not be reading any. If you do, you are breaking back-pressure across your system which causes all kinds of problems. In this case, loss of data due to dropped messages.

**Comment by jamilbk** [comment]
> I am not saying to re-implement it. I am saying it sounds like a bug in Phoenix that it is processing messages without handling them.


I see, I can try opening an issue on the Phoenix.Channel repo.

**Comment by jamilbk** [comment]
> If where you are delivering messages to isn't ready to handle messages, you should not be reading any. If you do, you are breaking back-pressure across your system which causes all kinds of problems. In this case, loss of data due to dropped messages.

I know this is a property of TCP, but is this how WebSocket rooms work in general too?

**Comment by thomaseizinger** [comment]
"WebSocket rooms" is a concept of Phoenix for all I know so I am not sure it makes sense to extrapolate here. WebSockets just give you a reliable, bi-directional stream.

It depends if you want reliable delivery of data. TCP aims to be reliable but it can only "help" you on the application layer if you make sure to only consume data from the stream if you can handle it. If you consume but drop it, the reliable delivery is broken.

**Comment by thomaseizinger** [comment]
> You probably don't even need to wait for the `init`. It looks like you're sending messages before phoenix has acknowledged your channel join:
> 
> ```
> client-1  | 2025-06-23T19:31:57.350Z TRACE wire::api::send: {"topic":"client","event":"phx_join","payload":null,"ref":5}
> client-1  | 2025-06-23T19:31:57.350Z TRACE wire::api::send: {"topic":"client","event":"create_flow","payload":{"resource_id":"ce795e05-0d3a-441a-920b-ed5ae21695af","connected_gateway_ids":[]},"ref":1}
> client-1  | 2025-06-23T19:31:57.350Z TRACE wire::api::send: {"topic":"client","event":"create_flow","payload":{"resource_id":"ce795e05-0d3a-441a-920b-ed5ae21695af","connected_gateway_ids":[]},"ref":2}
> client-1  | 2025-06-23T19:31:57.350Z TRACE wire::api::send: {"topic":"client","event":"create_flow","payload":{"resource_id":"ce795e05-0d3a-441a-920b-ed5ae21695af","connected_gateway_ids":[]},"ref":3}
> client-1  | 2025-06-23T19:31:57.350Z TRACE wire::api::send: {"topic":"client","event":"create_flow","payload":{"resource_id":"ce795e05-0d3a-441a-920b-ed5ae21695af","connected_gateway_ids":[]},"ref":4}
> client-1  | 2025-06-23T19:31:57.353Z TRACE wire::api::recv: {"event":"phx_reply","ref":5,"topic":"client","payload":{"status":"ok","response":{}}}
> ```

So if we track the room join and only send messages after that, it would work?

**Comment by jamilbk** [comment]
> So if we track the room join and only send messages after that, it would work?

I believe so.

I also wish this weren't necessary and we could just use plain WebSocket without having to worry about topics/rooms. Unfortunately Phoenix.Channel (an otherwise great library) seems to require a Topic: https://github.com/phoenixframework/phoenix/blob/v1.7.21/guides/real_time/channels.md#L1

We could presumably just use the lower-layer functionality in Phoenix.Socket to rely on WebSocket transport without channels. I do think the channel join we do is unnecessary.

That's a very large refactor though, and we'll need to keep the Channels around for older gateways/clients.

**Comment by thomaseizinger** [comment]
I wrote up my thoughts in #9649. Will work on a fix for this here tomorrow.

**Comment by jamilbk** [comment]
I'm not sure if this is fixed?

See [this failed run](https://github.com/firezone/firezone/actions/runs/15947022354/job/44982442938):


```
client-1  | 2025-06-28T18:39:44.201Z TRACE wire::api::send: {"topic":"client","event":"phx_join","payload":null,"ref":4}
client-1  | 2025-06-28T18:39:44.201Z TRACE wire::api::send: {"topic":"client","event":"create_flow","payload":{"resource_id":"85fc2899-d6da-4511-8799-8f0b4047d618","connected_gateway_ids":[]},"ref":1}
client-1  | 2025-06-28T18:39:44.201Z TRACE wire::api::send: {"topic":"client","event":"create_flow","payload":{"resource_id":"85fc2899-d6da-4511-8799-8f0b4047d618","connected_gateway_ids":[]},"ref":2}
client-1  | 2025-06-28T18:39:44.201Z TRACE wire::api::send: {"topic":"client","event":"create_flow","payload":{"resource_id":"85fc2899-d6da-4511-8799-8f0b4047d618","connected_gateway_ids":[]},"ref":3}
client-1  | 2025-06-28T18:39:44.204Z TRACE wire::api::recv: {"event":"phx_reply","ref":4,"topic":"client","payload":{"status":"ok","response":{}}}
```

**Comment by thomaseizinger** [comment]
Ah damn. Yeah just saw that the last refactoring I pushed on that PR was missing a `!` ...

**Comment by jamilbk** [comment]
This might still not be fixed.

See https://github.com/firezone/firezone/actions/runs/15998934938/job/45129213764


```
client-1  | 2025-07-01T12:19:18.552Z  INFO phoenix_channel: Connected to portal host=api
client-1  | 2025-07-01T12:19:18.552Z TRACE wire::api::send: {"topic":"client","event":"phx_join","payload":null,"ref":4}
client-1  | 2025-07-01T12:19:18.552Z TRACE wire::api::send: {"topic":"client","event":"create_flow","payload":{"resource_id":"91392d59-1586-4a2e-9afb-8819adc62651","connected_gateway_ids":[]},"ref":1}
client-1  | 2025-07-01T12:19:18.552Z TRACE wire::api::send: {"topic":"client","event":"create_flow","payload":{"resource_id":"91392d59-1586-4a2e-9afb-8819adc62651","connected_gateway_ids":[]},"ref":2}
client-1  | 2025-07-01T12:19:18.552Z TRACE wire::api::send: {"topic":"client","event":"create_flow","payload":{"resource_id":"91392d59-1586-4a2e-9afb-8819adc62651","connected_gateway_ids":[]},"ref":3}
client-1  | 2025-07-01T12:19:18.554Z TRACE wire::api::recv: {"event":"phx_reply","ref":4,"topic":"client","payload":{"status":"ok","response":{}}}
```

**Comment by thomaseizinger** [comment]
That is a compatibility test run so uses the last released version.
